#!/usr/bin/env ruby

require 'optparse'

ADJECTIVES = %w[
  sparkling
  gleaming
  whimsical
  effervescent
  bouncy
  glowing
  vibrant
  luminous
  playful
  serene
].freeze

NOUNS = %w[
  badger
  otter
  fox
  squirrel
  owl
  bear
  deer
  rabbit
  salmon
  trout
  tuna
  shark
  oak
  maple
  pine
  willow
].freeze

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: my-name-is [options]"

  opts.on("--plain", "Output name in plain text without ASCII art") do
    options[:plain] = true
  end
end.parse!

name = "#{ADJECTIVES.sample}-#{NOUNS.sample}"

if options[:plain]
  puts name
else
  puts "+--------------------+"
  puts "| #{name.ljust(18)} |"
  puts "+--------------------+"
end