#!/usr/bin/env ruby

require 'optparse'

ADJECTIVES = %w[
  sparkling
  gleaming
  whimsical
  effervescent
  bouncy
  glowing
  vibrant
  luminous
  playful
  serene
  jolly
  merry
  giddy
  charming
  delightful
  blissful
  radiant
  cheerful
  sunny
  dazzling
  fantastic
  fabulous
  splendid
  wondrous
  amazing
  awesome
  superb
  magnificent
  brilliant
  joyful
  ecstatic
  euphoric
  hilarious
  comical
  silly
  goofy
  zany
  quirky
  snazzy
  peppy
  perky
  sprightly
  lively
  bubbly
  gregarious
  optimistic
  upbeat
  dreamy
  fancy
  fluffy
  giggly
  happy
  kind
  lucky
  mirthful
  nimble
  nutty
  plucky
  quizzical
  rosy
  snuggly
  toasty
  witty
  zippy
].freeze

NOUNS = %w[
  badger
  otter
  fox
  squirrel
  owl
  bear
  deer
  rabbit
  salmon
  trout
  tuna
  shark
  oak
  maple
  pine
  willow
  dolphin
  penguin
  koala
  lemur
  meerkat
  platypus
  hedgehog
  chinchilla
  puffin
  narwhal
  octopus
  starfish
  seahorse
  clownfish
  jellyfish
  walrus
  beaver
  chipmunk
  ferret
  hamster
  iguana
  kangaroo
  llama
  moose
  newt
  opossum
  panda
  quokka
  raccoon
  sloth
  turtle
  unicorn
  vulture
  wombat
  yak
  zebra
  birch
  cedar
  elm
  fir
  hickory
  juniper
  larch
  mahogany
  nutmeg
  palm
  quince
  redwood
  spruce
  teak
  yew
].freeze

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: my-name-is [options]"

  opts.on("--plain", "Output name in plain text without ASCII art") do
    options[:plain] = true
  end
end.parse!

name = "#{ADJECTIVES.sample}-#{NOUNS.sample}"

if options[:plain]
  puts name
else
  puts "+--------------------+"
  puts "| #{name.ljust(18)} |"
  puts "+--------------------+"
end
